// This file wraps every page in the app.
// Anything placed here (Header, Navbar, Footer) appears on every single page automatically.

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Header from "./components/Header";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Breadcrumbs from "./components/Breadcrumbs";
import { ThemeProvider } from "./context/ThemeContext";

// Load Google fonts used across the site
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Basic page metadata (used for browser tab title, SEO, etc.)
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, // "children" is whatever page the user is currently viewing (Home, About, Feeds, etc.)
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        {/* ThemeProvider shares light/dark mode state with every page and component inside it */}
        <ThemeProvider>
          <Header />
          <Navbar />
          <Breadcrumbs />
          {children /* This is where the actual page content gets inserted */}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}